# Generated by Django 4.1.7 on 2023-03-08 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'В активном поиске'), (2, 'Открыт к предложениям'), (3, 'Не ищу работу')], default=1, verbose_name='Статус')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('specialty', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Специальность')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Зароботная плата')),
                ('education', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Образование')),
                ('experience', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Опыт')),
                ('portfolio', models.TextField(blank=True, null=True, verbose_name='Портфолио')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон для связи')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
